### ISSUE TITLE
FR1. Home page task overview

### ISSUE THREAD

**Issue by eu7702** [WSU-4110/Organyze-Bullet#1]
|FR1. Home page task overview|
|---|
|**Goal**: After user login, the application should show a dashboard of notebooks and pending tasks.|
|**Stakeholders:** Users|
|**Description:** After a user logs on to a native application or web app, the user should see a list of their pending tasks, a notebook activity log, recently used notebooks, any notebooks shared with the user, and a list of starred notebooks that are pinned to the top of the dashboard for easy access.|
|**Origin:** Requirements Meeting|
|**Version:** 1.0|
|**Date:** 10/01/2021|
|**Priority:** Medium|

**Comment by Dedvukaj** [comment]
homepage shows the notebooks with the tasks inside the notebook that need to be worked on
