### ISSUE TITLE
FR11. User authentication

### ISSUE THREAD

**Issue by eu7702** [WSU-4110/Organyze-Bullet#11]
FR11. User authentication
|---|
|**Goal**: Verify the identity of the user seeking to gain access to the system.|
|**Stakeholders:** Users, Admin|
|**Description:** A new user will need to set up a new account with a username and secure password. User can create account with Google e-mail. An account created with Google log in will allow user to one-click log in. An account created with other e-mail service will need to sign in with their username and password to verify their identity and gain access to the system.|
|**Origin:** Requirements Meeting|
|**Version:** 1.0|
|**Date:** 10/01/2021|
|**Priority:** High|

**Comment by teamvista** [comment]
Still needs Google login, but we're almost done here.
Email and password login is functional.

**Comment by Ibrahim-gw8885** [comment]
Google authorization is set.
