### ISSUE TITLE
NFR5. Cross-platform application

### ISSUE THREAD

**Issue by eu7702** [WSU-4110/Organyze-Bullet#21]
|NFR5. Cross-platform application|
|---|
|**Goal**: The app will have cross-platform support with similar interfaces for all platforms.|
|**Stakeholders:** Users, Admin|
|**Description:** Compatibility with other operating systems should be available, across Web, iOS, Android, and Desktop.|
|**Origin:** Requirements Meeting|
|**Version:** 1.0|
|**Date:** 10/01/2021|
|**Priority:** High|

**Comment by Dedvukaj** [comment]
worked across ios, android and web app to fix compatibility issues and bugs.
